filetype plugin indent on
syntax on
set fileencodings=utf-8,gb2312,gbk,gb18030,big  
set termencoding=utf-8  
set encoding=utf-8
set tabstop=4
set expandtab
set shiftwidth=4
set number
set noswapfile
